default_platform(:ios)

platform :ios do
  desc "Build and run the Debug configuration"
  lane :build_debug do
    build_app(
      scheme: "HabitTracker-Debug",
      configuration: "Debug",
      export_method: "development"
    )
  end

  desc "Build and run the Development configuration"
  lane :build_dev do
    build_app(
      scheme: "HabitTracker-Development",
      configuration: "Release-Development",
      export_method: "development"
    )
  end

  desc "Build and deploy the Production configuration to TestFlight"
  lane :build_prod do
    build_app(
      scheme: "HabitTracker-Production",
      configuration: "Release-Production",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end

